### ISSUE TITLE
Testnet api endpoint lead to json error

### ISSUE THREAD

**Issue by TotalSX** [EtWnn/ScanWatch#20]
After

Client.py:
"""BASE_BSC_URL = "https://api.bscscan.com/api" # mainnet"""
BASE_BSC_URL = "https://api-testnet.bscscan.com/api" # testnet

I'm got an Error:
Traceback (most recent call last):
  File "scanw.py", line 11, in <module>
    manager.update_all_transactions()
.........
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Mainnet endpoint works fine. Possible solution?

**Comment by EtWnn** [comment]
Hi TotalSX,

Thanks for raising an issue!
I didn't have the testnet in mind when developing this but I will look if a solution can implemented to correct this

**Comment by TotalSX** [comment]
It's really strange tbh, requests/responses are same from API's, only difference is endpoint url

**Comment by EtWnn** [comment]
I will investigate this today or tomorrow.
In any case, changes have to be made to support test net. Otherwise their will be collisions between the data of the main and the test nets

**Comment by EtWnn** [comment]
The JSON error is caused by a 403 http error from the test net api
Fix  + test nets support in the pipeline

**Comment by EtWnn** [comment]
The above PR should fix the issue
