### ISSUE TITLE
discussion tab + feature

### ISSUE THREAD

**Issue by TotalSX** [EtWnn/ScanWatch#23]
Hi. Repository discussion tab seems missing you can add it in settings.

Feature request:
Get address current erc20/erc721 (bep20/bep721) holdings.

My idea of implementation:
1) get inputs and outputs separately
2) compare them
3) remove spent transactions
4) result - all unspent inputs

My implementation of bep721 holdings:
```
from ScanWatch import ScanManager
from ScanWatch.utils.enums import NETWORK, TRANSACTION

api_token = ""
address = "0x8477f08df0d70f3b19e6241dcb1757363741ed7e"

manager = ScanManager(address, NETWORK.BSC, api_token, "test")

# manager.get_transactions(TRANSACTION.NORMAL)  # normal transactions

manager.update_all_transactions()

result = manager.get_transactions(TRANSACTION.ERC721)

trans_in = []
trans_out = []

print('Transactions: ')
for res in result:
    if res['from'] == address:
        trans_out.append(res)
        side = 'out'
    else:
        trans_in.append(res)
        side = 'in'

    print(f"from: {res['from']} / {side} / to: {res['to']} / contract: {res['contractAddress']} / token: {res['tokenID']} - {res['tokenName']} - {res['tokenSymbol']}")

final = trans_in

for x in trans_in:
    for out in trans_out:
        if (out['contractAddress'] == x['contractAddress'] and
                out['tokenID'] == x['tokenID'] and
                out['tokenName'] == x['tokenName'] and
                out['tokenSymbol'] == x['tokenSymbol']):
            final.remove(x)

print('Holdings: ')
for res in final:
    print(f"from: {res['from']} / to: {res['to']} / contract: {res['contractAddress']} / token: {res['tokenID']} - {res['tokenName']} - {res['tokenSymbol']}")
```

I'm not clearly sure if this is the right way of implementation (don't know how this will work if transactions failed etc.)

If you can natively implement this functional into library that's would be nice. Maybe you can do this with better/safer/optimized way

**Comment by EtWnn** [comment]
Good suggestion for the discussion tab, it is done

For the erc20/erc721 holdings feature, it would be a good idea.
I can see two ways of doing this:
- If you are not in a hurry, I will implement it next week in a PR
- Otherwise you can do a PR and I will manage some time to review it

If you want to do a PR, I think a more efficient solution would be to count the holdings in one loop, while maintaining a dictionary of the number of items per token ID for erc721 and per token name for erc20

**Comment by TotalSX** [comment]
I would like to do a PR but I don't have much experience and my best implementation is shown above :(
And I'm not clearly sure if this would give stable results every time (in case there any failed transactions). Btw I have no idea how this could possible be done in one loop, because we have different tokenId/tokenName/contract and somehow we need to compare them with all inputs and outputs.
Would be nice to see your implementation

**Comment by EtWnn** [comment]
Hi @TotalSX ,
My implementation is in the [PR#29](https://github.com/EtWnn/ScanWatch/pull/29).
Does that fit your needs?

**Comment by TotalSX** [comment]
Hello @EtWnn , yep everything works. Thanks
