### ISSUE TITLE
Is there a work around for "First operation on an asset is a removal"?

### ISSUE THREAD

**Issue by uBadRequest** [EtWnn/ScanWatch#33]
https://github.com/EtWnn/ScanWatch/blob/43a7e15282e6687c610acee3ae9b5fd85ed92d8e/ScanWatch/ScanManager.py#LL104C27-L104C37

Can you work around this without raising an exception?

**Comment by EtWnn** [comment]
This error is useful: it signals that a transaction tried to remove some tokens from an address when this asset was never seen previously on the address.

I can see two reasons for this behaviour:
- There is a bug in this library and some transactions were not fetched or wrongly sorted
- The class was not correctly used

Can you show me how you made this bug occur?

**Comment by EtWnn** [comment]
This issue was closed due to lack of response from the user
